name: Deploy Portfolio Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Type check
        run: npm run type-check
        
      - name: Lint
        run: npm run lint
        
      - name: Build and optimize
        run: npm run build
        env:
          NEXT_PUBLIC_SITE_URL: ${{ secrets.SITE_URL || 'https://ki6h.github.io' }}
          
      - name: Run tests
        run: npm test
        
      - name: Optimize assets
        run: npm run optimize
        
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Purge cache and verify deployment
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          curl -X POST "https://api.github.com/repos/${{ github.repository }}/pages/builds" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json"
          
          echo "Deployment complete! Site will be available at: ${{ secrets.SITE_URL || 'https://ki6h.github.io' }}"

